apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hsm-keys.strid.tech
spec:
  group: strid.tech
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hsm:
                  type: string
                key:
                  type: string
                secret:
                  type: string
                akv:
                  type: string
                secretName:
                  type: string
              required:
                - secretName
                - key
                - secret
                - akv
          required:
            - spec
  scope: Namespaced
  names:
    plural: hsm-keys
    singular: hsm-key
    kind: HsmKey
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: akv-keys.strid.tech
spec:
  group: strid.tech
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                akv:
                  type: string
                secret:
                  type: string
                key:
                  type: string
                secretName:
                  type: string
              required:
                - secretName
                - key
                - secret
                - akv
          required:
            - spec
  scope: Namespaced
  names:
    plural: akv-keys
    singular: akv-key
    kind: AkvKey
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cert-keys.strid.tech
spec:
  group: strid.tech
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                akv:
                  type: string
                cert:
                  type: string
                secretName:
                  type: string
              required:
                - secretName
                - cert
                - akv
          required:
            - spec
  scope: Namespaced
  names:
    plural: cert-keys
    singular: cert-key
    kind: CertKey
