apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-secret-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crd-secret-controller
  template:
    metadata:
      labels:
        app: crd-secret-controller
    spec:
      serviceAccountName: crd-secret-controller-sa
      containers:
        - name: controller
          image: stabdevacr01.azurecr.io/akv-cert-secret:126
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-secret-controller-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-secret-controller-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "patch", "update"]
  - apiGroups: ["strid.tech"]
    resources: ["hsm-keys"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-secret-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-secret-controller-role
subjects:
  - kind: ServiceAccount
    name: crd-secret-controller-sa
    namespace: kube-system
