apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-secret-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crd-secret-controller
  template:
    metadata:
      labels:
        app: crd-secret-controller
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: hsm-ingress-secret-creator
      containers:
        - name: controller
          image: stabdevacr01.azurecr.io/akv-cert-secret:153
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hsm-ingress-secret-creator
  namespace: kube-system
  annotations:
    azure.workload.identity/client-id: "23b6b41a-de18-4890-9922-84055817cf18"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-secret-controller-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "patch", "update"]
  - apiGroups: ["strid.tech"]
    resources: ["hsm-keys", "akv-keys", "cert-keys"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-secret-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-secret-controller-role
subjects:
  - kind: ServiceAccount
    name: hsm-ingress-secret-creator
    namespace: kube-system
