apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hsm-ingress-secret-controller.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "patch", "update"]
  - apiGroups: ["strid.tech"]
    resources: ["hsm-keys", "akv-keys", "cert-keys"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
