apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "hsm-ingress-secret-creator" | quote }}
  namespace: {{ .Values.namespace | default "kube-system" | quote }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.annotations.clientId | default "" | quote }}