name: Container
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          # TODO: Should we setup our own cache?
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
            extra-substituters = https://ocaml.nix-cache.com
            extra-trusted-public-keys = ocaml.nix-cache.com-1:/xI2h2+56rwFfKyyFVbkJSeGqSIYMC/Je+7XXqGKDIY=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build nix packages
        run: nix build .#container
      - name: devenv test
        run: nix develop --no-pure-eval -c devenv test
